Normalization Problem


In [1]:
import numpy as np

X = np.random.randn(5, 5)

mean = X.mean()
std_dev = X.std()

X_normalized = (X - mean) / std_dev

np.save('X_normalized.npy', X_normalized)

print("Original array X:\n", X)
print("Normalized array X_normalized:\n", X_normalized)


Original array X:
 [[-0.15484357  0.09274169  1.05465822  0.83009405 -0.10951156]
 [ 0.29669606  0.43970932 -1.5112456  -1.0591347  -0.43290009]
 [-0.84749329  0.81184922  1.4607752   0.29489517  0.54851943]
 [ 0.6406357   0.29643882 -0.07773234 -0.63669976 -1.60502333]
 [-1.85236311  0.57931284  0.3753593   0.29538989 -0.00453033]]
Normalized array X_normalized:
 [[-0.17396824  0.12541823  1.28859246  1.01704368 -0.1191516 ]
 [ 0.37204511  0.54498042 -1.81416447 -1.26746034 -0.51020133]
 [-1.0115381   0.99498156  1.77967956  0.36986742  0.67655641]
 [ 0.78794577  0.37173404 -0.08072335 -0.75664114 -1.92756291]
 [-2.22665255  0.71379259  0.46716672  0.37046565  0.00779441]]


Divisible by 3 Problem


In [3]:
import numpy as np

integers = np.arange(1, 101)

squares = integers ** 2

A = squares.reshape(10, 10)

divisible_by_3 = A[A % 3 == 0]

np.save('div_by_3.npy', divisible_by_3)

print("Elements divisible by 3:\n", divisible_by_3)

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
